In [ ]:
import pandas as pd

#file names
pos_file = "../../raw/cedar_positive.csv"
neg_file = "../../raw/cedar_negative.csv"
output_file = "../../processed/cedar_combined.csv"

In [2]:
#load files
def load_cedar(filepath, label): 
    with open(filepath, 'r') as f:
        first_line = f.readline() 
    sep = "\t" if "\t" in first_line else ","

    #read file
    df = pd.read_csv(filepath, sep=sep, dtype=str)

    #add label column
    df['label'] = label
    return df

In [3]:
df_pos = load_cedar(pos_file, "Positive") 
df_neg = load_cedar(neg_file, "Negative")

#combine dataframes
df = pd.concat([df_pos, df_neg], ignore_index=True)
df.head()

,Epitope ID - CEDAR IRI,Epitope - Object Type,Epitope - Name,Epitope - Modified Residue(s),Epitope - Modifications,Epitope - Starting Position,Epitope - Ending Position,Epitope - IRI,Epitope - Synonyms,Epitope - Source Molecule,...,Related Object - Synonyms,Related Object - Source Molecule,Related Object - Source Molecule IRI,Related Object - Molecule Parent,Related Object - Molecule Parent IRI,Related Object - Source Organism,Related Object - Source Organism IRI,Related Object - Species,Related Object - Species IRI,label
0,https://cedar.iedb.org/epitope/551,Linear peptide,ACDPHSGHFV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"Cell division protein kinase 4, PSK-J3, CDK4",Cyclin-dependent kinase 4,https://www.uniprot.org/uniprot/P11802.2,Cyclin-dependent kinase 4,http://www.uniprot.org/uniprot/P11802,Homo sapiens (human),http://purl.obolibrary.org/obo/NCBITaxon_9606,Homo sapiens,http://purl.obolibrary.org/obo/NCBITaxon_9606,Positive
1,https://cedar.iedb.org/epitope/3147,Linear peptide,AMLGTHTMEV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"immunoglobulin heavy chain junction region, pa...",http://www.ncbi.nlm.nih.gov/protein/MCC79800.1,NaN,NaN,Homo sapiens (human),http://purl.obolibrary.org/obo/NCBITaxon_9606,Homo sapiens,http://purl.obolibrary.org/obo/NCBITaxon_9606,Positive
2,https://cedar.iedb.org/epitope/4966,Linear peptide,ATGFKQSSK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"(1:Renal carcinoma antigen NY-REN-26, BCR, BCR...",Tyrosine-protein kinase ABL1,https://www.uniprot.org/uniprot/P00519.4,Tyrosine-protein kinase ABL1,http://www.uniprot.org/uniprot/P00519,Homo sapiens (human),http://purl.obolibrary.org/obo/NCBITaxon_9606,Homo sapiens,http://purl.obolibrary.org/obo/NCBITaxon_9606,Positive
3,https://cedar.iedb.org/epitope/14672,Linear peptide,EVDPIGHLY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,melanoma antigen 2; cancer/testis antigen fami...,melanoma-associated antigen 2 [Homo sapiens],http://www.ncbi.nlm.nih.gov/protein/NP_0012694...,Melanoma-associated antigen 2,http://www.uniprot.org/uniprot/P43356,Homo sapiens (human),http://purl.obolibrary.org/obo/NCBITaxon_9606,Homo sapiens,http://purl.obolibrary.org/obo/NCBITaxon_9606,Positive
4,https://cedar.iedb.org/epitope/19558,Linear peptide,GFKQSSKAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"(1:bcr), (2:Abelson murine leukemia viral onco...",Tyrosine-protein kinase ABL1,https://www.uniprot.org/uniprot/P00519.4,Tyrosine-protein kinase ABL1,http://www.uniprot.org/uniprot/P00519,Homo sapiens (human),http://purl.obolibrary.org/obo/NCBITaxon_9606,Homo sapiens,http://purl.obolibrary.org/obo/NCBITaxon_9606,Positive

In [4]:
new_cols = []

for col in df.columns: 
    col = col.replace(" - ", "_")
    col = col.replace(" ", "_")
    col = col.lower() 
    new_cols.append(col)

df.columns = new_cols
print(df.columns)

Index(['epitope_id_cedar_iri', 'epitope_object_type', 'epitope_name',
       'epitope_modified_residue(s)', 'epitope_modifications',
       'epitope_starting_position', 'epitope_ending_position', 'epitope_iri',
       'epitope_synonyms', 'epitope_source_molecule',
       'epitope_source_molecule_iri', 'epitope_molecule_parent',
       'epitope_molecule_parent_iri', 'epitope_source_organism',
       'epitope_source_organism_iri', 'epitope_species', 'epitope_species_iri',
       'epitope_mutation', 'related_object_epitope_relation',
       'related_object_object_type', 'related_object_name',
       'related_object_starting_position', 'related_object_ending_position',
       'related_object_iri', 'related_object_synonyms',
       'related_object_source_molecule', 'related_object_source_molecule_iri',
       'related_object_molecule_parent', 'related_object_molecule_parent_iri',
       'related_object_source_organism', 'related_object_source_organism_iri',
       'related_object_species', 'related_object_species_iri', 'label'],
      dtype='object')

In [5]:
df.head()

,epitope_id_cedar_iri,epitope_object_type,epitope_name,epitope_modified_residue(s),epitope_modifications,epitope_starting_position,epitope_ending_position,epitope_iri,epitope_synonyms,epitope_source_molecule,...,related_object_synonyms,related_object_source_molecule,related_object_source_molecule_iri,related_object_molecule_parent,related_object_molecule_parent_iri,related_object_source_organism,related_object_source_organism_iri,related_object_species,related_object_species_iri,label
0,https://cedar.iedb.org/epitope/551,Linear peptide,ACDPHSGHFV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"Cell division protein kinase 4, PSK-J3, CDK4",Cyclin-dependent kinase 4,https://www.uniprot.org/uniprot/P11802.2,Cyclin-dependent kinase 4,http://www.uniprot.org/uniprot/P11802,Homo sapiens (human),http://purl.obolibrary.org/obo/NCBITaxon_9606,Homo sapiens,http://purl.obolibrary.org/obo/NCBITaxon_9606,Positive
1,https://cedar.iedb.org/epitope/3147,Linear peptide,AMLGTHTMEV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"immunoglobulin heavy chain junction region, pa...",http://www.ncbi.nlm.nih.gov/protein/MCC79800.1,NaN,NaN,Homo sapiens (human),http://purl.obolibrary.org/obo/NCBITaxon_9606,Homo sapiens,http://purl.obolibrary.org/obo/NCBITaxon_9606,Positive
2,https://cedar.iedb.org/epitope/4966,Linear peptide,ATGFKQSSK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"(1:Renal carcinoma antigen NY-REN-26, BCR, BCR...",Tyrosine-protein kinase ABL1,https://www.uniprot.org/uniprot/P00519.4,Tyrosine-protein kinase ABL1,http://www.uniprot.org/uniprot/P00519,Homo sapiens (human),http://purl.obolibrary.org/obo/NCBITaxon_9606,Homo sapiens,http://purl.obolibrary.org/obo/NCBITaxon_9606,Positive
3,https://cedar.iedb.org/epitope/14672,Linear peptide,EVDPIGHLY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,melanoma antigen 2; cancer/testis antigen fami...,melanoma-associated antigen 2 [Homo sapiens],http://www.ncbi.nlm.nih.gov/protein/NP_0012694...,Melanoma-associated antigen 2,http://www.uniprot.org/uniprot/P43356,Homo sapiens (human),http://purl.obolibrary.org/obo/NCBITaxon_9606,Homo sapiens,http://purl.obolibrary.org/obo/NCBITaxon_9606,Positive
4,https://cedar.iedb.org/epitope/19558,Linear peptide,GFKQSSKAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"(1:bcr), (2:Abelson murine leukemia viral onco...",Tyrosine-protein kinase ABL1,https://www.uniprot.org/uniprot/P00519.4,Tyrosine-protein kinase ABL1,http://www.uniprot.org/uniprot/P00519,Homo sapiens (human),http://purl.obolibrary.org/obo/NCBITaxon_9606,Homo sapiens,http://purl.obolibrary.org/obo/NCBITaxon_9606,Positive

In [6]:
#pick relevant columns 
clean = pd.DataFrame()

clean["mt_seq"] = df["epitope_name"].values
clean["wt_seq"] = df["related_object_name"].values
clean["mutation"] = df["epitope_mutation"].values
clean["epitope_relation"] = df["related_object_epitope_relation"].values
clean["source_molecule"] = df["epitope_source_molecule"].values
clean["label"] = df["label"].values

clean.head()

,mt_seq,wt_seq,mutation,epitope_relation,source_molecule,label
0,ACDPHSGHFV,ARDPHSGHFV,R24C,in-frame neo-epitope,NaN,Positive
1,AMLGTHTMEV,AMLSPHAMDV,NaN,in-frame neo-epitope,NaN,Positive
2,ATGFKQSSK,b2a2,NaN,fusion neo-epitope,NaN,Positive
3,EVDPIGHLY,EVVPISHLY,NaN,in-frame neo-epitope,NaN,Positive
4,GFKQSSKAL,NaN,NaN,fusion neo-epitope,NaN,Positive

In [7]:
#clean and filter

#checker
print(len(clean))

#uppercase and strip 
clean["mt_seq"] = clean["mt_seq"].str.strip().str.upper()
clean["wt_seq"] = clean["wt_seq"].str.strip().str.upper()

#drop rows with no peptide seq
clean = clean.dropna(subset=["mt_seq"]) 
print("after removing empty rows:", len(clean))

13346
after removing empty rows: 13346

In [8]:
#filter out invalid aa
valid_aa = set("ACDEFGHIKLMNPQRSTVWY")
def is_valid(seq): 
    if not isinstance(seq, str): 
        return False
    for aa in seq:
        if aa not in valid_aa: 
            return False
    return True
mask = clean["mt_seq"].apply(is_valid)
clean = clean[mask]
mask2 = clean["wt_seq"].apply(is_valid)
clean = clean[mask2]
print("after filtering invalid aa:", len(clean))

after filtering invalid aa: 12740

In [9]:
#keep only inframe rows
mask = clean["epitope_relation"].str.contains("in-frame", case=False, na=True)
clean = clean[mask]
print("after filtering in-frame:", len(clean))

after filtering in-frame: 12265

In [10]:
#check if wildtype is valid
not_empty = clean["wt_seq"].notna()
valid_seq = clean["wt_seq"].apply(is_valid)

#combine
clean["has_wildtype"] = not_empty & valid_seq
print("after filtering wildtype:", len(clean))

after filtering wildtype: 12265

In [ ]:
##REMOVE DUPLICATIONS

#positives per peptide
pos_count = {}

for i, row in clean.iterrows(): 
    pep = row["mt_seq"]
    label = row["label"]
    if pep not in pos_count: 
        pos_count[pep] = 0
    if label == "Positive":
        pos_count[pep] += 1

#drop duplicates
clean = clean.drop_duplicates(["mt_seq", "wt_seq"].copy())

#assign labels
new_labels = []
for pep in clean["mt_seq"]:
    if pos_count[pep] > 0: 
        new_labels.append("1")
    else: 
        new_labels.append("0")
clean["label"] = new_labels
print(len(clean))

11657

/var/folders/jv/f3z3s_9n7mz98t8xqgd9b1_00000gn/T/ipykernel_12846/3260900584.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean["label"] = new_labels

In [14]:
##SUMMARY
n_pos = 0
n_neg = 0
for label in clean["label"]:
    if label == "1":
        n_pos += 1
    else: 
        n_neg += 1
print("total peptides:", len(clean))
print("positive:", n_pos)
print("negative:", n_neg)

total peptides: 11657
positive: 2554
negative: 9103

In [15]:
clean.head()

,mt_seq,wt_seq,mutation,epitope_relation,source_molecule,label
0,ACDPHSGHFV,ARDPHSGHFV,R24C,in-frame neo-epitope,NaN,1
1,AMLGTHTMEV,AMLSPHAMDV,NaN,in-frame neo-epitope,NaN,1
3,EVDPIGHLY,EVVPISHLY,NaN,in-frame neo-epitope,NaN,1
5,GVYDGEEHSV,GAYDGEEH,NaN,in-frame neo-epitope,NaN,1
7,ITKKVADLVGF,KKVADLI,NaN,in-frame neo-epitope,NaN,1

In [16]:
#saving output file
clean.to_csv(output_file, index=False)