In [1]:
#load data
tcell_file = "../../raw/tcell_full_v3.csv"
mhc_file = "../../raw/mhc_ligand_full.csv"

In [3]:
##load tcell and mhc exports
import pandas as pd 

#have 2 row headers
tcell_df = pd.read_csv(tcell_file, header=[0,1], low_memory = False)
tcell_df.columns = [f"{a} - {b}" for a,b in tcell_df.columns]
tcell_df.head()

,Assay ID - CEDAR IRI,Reference - CEDAR IRI,Reference - Type,Reference - PMID,Reference - Submission ID,Reference - Authors,Reference - Journal,Reference - Date,Reference - Title,Epitope - CEDAR IRI,...,Assay Antigen - Ending Position,Assay Antigen - IRI,Assay Antigen - Source Molecule,Assay Antigen - Source Molecule IRI,Assay Antigen - Molecule Parent,Assay Antigen - Molecule Parent IRI,Assay Antigen - Source Organism,Assay Antigen - Source Organism IRI,Assay Antigen - Species,Assay Antigen - Species IRI
0,https://cedar.iedb.org/assay/29,https://cedar.iedb.org/reference/274,Literature,15448372.0,NaN,Yi-Hsiang Huang; Mi-Hua Tao; Cheng-Po Hu; Wan-...,J Gen Virol,2004,Identification of novel HLA-A*0201-restricted ...,https://cedar.iedb.org/epitope/31803,...,34.0,NaN,large delta antigen,http://www.ncbi.nlm.nih.gov/protein/AAG26087.1,Large delta antigen,http://www.uniprot.org/uniprot/P29996,Hepatitis delta virus TW2667,https://ontology.iedb.org/taxon/10000523,Hepatitis delta virus,http://purl.obolibrary.org/obo/NCBITaxon_12475
1,https://cedar.iedb.org/assay/47,https://cedar.iedb.org/reference/275,Literature,15519708.0,NaN,Olivier B Engler; Reto A Schwendener; Wen Juan...,Vaccine,2004,A liposomal peptide vaccine inducing CD8+ T ce...,https://cedar.iedb.org/epitope/9203,...,140.0,NaN,Genome polyprotein,https://www.uniprot.org/uniprot/P26664.3,Genome polyprotein,http://www.uniprot.org/uniprot/P27958,hepatitis C virus genotype 1a,http://purl.obolibrary.org/obo/NCBITaxon_2847144,Hepacivirus hominis,http://purl.obolibrary.org/obo/NCBITaxon_3052230
2,https://cedar.iedb.org/assay/105,https://cedar.iedb.org/reference/274,Literature,15448372.0,NaN,Yi-Hsiang Huang; Mi-Hua Tao; Cheng-Po Hu; Wan-...,J Gen Virol,2004,Identification of novel HLA-A*0201-restricted ...,https://cedar.iedb.org/epitope/31803,...,34.0,NaN,large delta antigen,http://www.ncbi.nlm.nih.gov/protein/AAG26087.1,Large delta antigen,http://www.uniprot.org/uniprot/P29996,Hepatitis delta virus TW2667,https://ontology.iedb.org/taxon/10000523,Hepatitis delta virus,http://purl.obolibrary.org/obo/NCBITaxon_12475
3,https://cedar.iedb.org/assay/107,https://cedar.iedb.org/reference/274,Literature,15448372.0,NaN,Yi-Hsiang Huang; Mi-Hua Tao; Cheng-Po Hu; Wan-...,J Gen Virol,2004,Identification of novel HLA-A*0201-restricted ...,https://cedar.iedb.org/epitope/31803,...,34.0,NaN,large delta antigen,http://www.ncbi.nlm.nih.gov/protein/AAG26087.1,Large delta antigen,http://www.uniprot.org/uniprot/P29996,Hepatitis delta virus TW2667,https://ontology.iedb.org/taxon/10000523,Hepatitis delta virus,http://purl.obolibrary.org/obo/NCBITaxon_12475
4,https://cedar.iedb.org/assay/443,https://cedar.iedb.org/reference/328,Literature,15104676.0,NaN,V Corbière; H Nicolay; V Russo; V Stroobant; V...,Tissue Antigens,2004,Identification of a MAGE-1 peptide recognized ...,https://cedar.iedb.org/epitope/28958,...,NaN,https://www.uniprot.org/uniprot/P43355.1,NaN,NaN,NaN,NaN,Homo sapiens,http://purl.obolibrary.org/obo/NCBITaxon_9606,Homo sapiens,http://purl.obolibrary.org/obo/NCBITaxon_9606

In [4]:
tcell_df.columns.tolist()

['Assay ID - CEDAR IRI',
 'Reference - CEDAR IRI',
 'Reference - Type',
 'Reference - PMID',
 'Reference - Submission ID',
 'Reference - Authors',
 'Reference - Journal',
 'Reference - Date',
 'Reference - Title',
 'Epitope - CEDAR IRI',
 'Epitope - Object Type',
 'Epitope - Name',
 'Epitope - Reference Name',
 'Epitope - Modified residues',
 'Epitope - Modifications',
 'Epitope - Starting Position',
 'Epitope - Ending Position',
 'Epitope - IRI',
 'Epitope - Synonyms',
 'Epitope - Source Molecule',
 'Epitope - Source Molecule IRI',
 'Epitope - Molecule Parent',
 'Epitope - Molecule Parent IRI',
 'Epitope - Source Organism',
 'Epitope - Source Organism IRI',
 'Epitope - Species',
 'Epitope - Species IRI',
 'Epitope - Mutation',
 'Epitope - Epitope Comments',
 'Related Object - Epitope Relation',
 'Related Object - Object Type',
 'Related Object - Name',
 'Related Object - Starting Position',
 'Related Object - Ending Position',
 'Related Object - IRI',
 'Related Object - Synonyms',
 'Related Object - Source Molecule',
 'Related Object - Source Molecule IRI',
 'Related Object - Molecule Parent',
 'Related Object - Molecule Parent IRI',
 'Related Object - Source Organism',
 'Related Object - Source Organism IRI',
 'Related Object - Species',
 'Related Object - Species IRI',
 'Host - Name',
 'Host - IRI',
 'Host - Geolocation',
 'Host - Geolocation IRI',
 'Host - Sex',
 'Host - Age',
 'Host - MHC Present',
 '1st in vivo Process - Process Type',
 '1st in vivo Process - Disease',
 '1st in vivo Process - Disease IRI',
 '1st in vivo Process - Disease Stage',
 '1st immunogen - Epitope Relation',
 '1st immunogen - Object Type',
 '1st immunogen - Name',
 '1st immunogen - Reference Name',
 '1st immunogen - Starting Position',
 '1st immunogen - Ending Position',
 '1st immunogen - IRI',
 '1st immunogen - Source Molecule',
 '1st immunogen - Source Molecule IRI',
 '1st immunogen - Molecule Parent',
 '1st immunogen - Molecule Parent IRI',
 '1st immunogen - Source Organism',
 '1st immunogen - Source Organism IRI',
 '1st immunogen - Species',
 '1st immunogen - Species IRI',
 '1st immunogen - Adjuvants',
 '1st immunogen - Route',
 '1st immunogen - Dose Schedule',
 '2nd in vivo Process - Process Type',
 '2nd in vivo Process - Disease',
 '2nd in vivo Process - Disease IRI',
 '2nd in vivo Process - Disease Stage',
 '2nd immunogen - Epitope Relation',
 '2nd immunogen - Object Type',
 '2nd immunogen - Name',
 '2nd immunogen - Reference Name',
 '2nd immunogen - Starting Position',
 '2nd immunogen - Ending Position',
 '2nd immunogen - IRI',
 '2nd immunogen - Source Molecule',
 '2nd immunogen - Source Molecule IRI',
 '2nd immunogen - Molecule Parent',
 '2nd immunogen - Molecule Parent IRI',
 '2nd immunogen - Source Organism',
 '2nd immunogen - Source Organism IRI',
 '2nd immunogen - Species',
 '2nd immunogen - Species IRI',
 '2nd immunogen - Adjuvants',
 '2nd immunogen - Route',
 '2nd immunogen - Dose Schedule',
 'In vitro Process - Process Type',
 'in vitro Responder Cell - Name',
 'in vitro Responder Cell - IRI',
 'in vitro Stimulator Cell - Name',
 'in vitro Stimulator Cell - IRI',
 'in vitro immunogen - Epitope Relation',
 'in vitro immunogen - Object Type',
 'in vitro immunogen - Name',
 'in vitro immunogen - Reference Name',
 'in vitro immunogen - Starting Position',
 'in vitro immunogen - Ending Position',
 'in vitro immunogen - IRI',
 'in vitro immunogen - Source Molecule',
 'in vitro immunogen - Source Molecule IRI',
 'in vitro immunogen - Molecule Parent',
 'in vitro immunogen - Molecule Parent IRI',
 'in vitro immunogen - Source Organism',
 'in vitro immunogen - Source Organism IRI',
 'in vitro immunogen - Species',
 'in vitro immunogen - Species IRI',
 'Adoptive Transfer - Flag',
 'Adoptive Transfer - Comments',
 'Immunization - Comments',
 'Assay - Location of Assay Data in Reference',
 'Assay - Method',
 'Assay - Response measured',
 'Assay - Units',
 'Assay - IRI',
 'Assay - Qualitative Measurement',
 'Assay - Measurement Inequality',
 'Assay - Quantitative measurement',
 'Assay - Number of Subjects Tested',
 'Assay - Number of Subjects Positive',
 'Assay - Response Frequency (%)',
 'Assay - Comments',
 'Effector Cell - Source Tissue',
 'Effector Cell - Source Tissue IRI',
 'Effector Cell - Name',
 'Effector Cell - IRI',
 'Effector Cell - Culture Condition',
 'Effector Cell - TCR Name',
 'Complex - PDB ID',
 'Antigen Presenting Cell - Source Tissue',
 'Antigen Presenting Cell - Source Tissue IRI',
 'Antigen Presenting Cell - Name',
 'Antigen Presenting Cell - IRI',
 'Antigen Presenting Cell - Culture Condition',
 'MHC Restriction - Name',
 'MHC Restriction - IRI',
 'MHC Restriction - Evidence Code',
 'MHC Restriction - Evidence IRI',
 'MHC Restriction - Class',
 'Assay Antigen - Epitope Relation',
 'Assay Antigen - Object Type',
 'Assay Antigen - Name',
 'Assay Antigen - Reference Name',
 'Assay Antigen - Starting Position',
 'Assay Antigen - Ending Position',
 'Assay Antigen - IRI',
 'Assay Antigen - Source Molecule',
 'Assay Antigen - Source Molecule IRI',
 'Assay Antigen - Molecule Parent',
 'Assay Antigen - Molecule Parent IRI',
 'Assay Antigen - Source Organism',
 'Assay Antigen - Source Organism IRI',
 'Assay Antigen - Species',
 'Assay Antigen - Species IRI']

In [5]:
mhc_df = pd.read_csv(mhc_file, header=[0,1], low_memory = True)
mhc_df.columns = [f"{a} - {b}" for a,b in mhc_df.columns]
mhc_df.head()

/var/folders/jv/f3z3s_9n7mz98t8xqgd9b1_00000gn/T/ipykernel_5828/651717742.py:1: DtypeWarning: Columns (6,12,13,14,17,18,27,28,29,30,31,35,36,37,38,39,40,41,42,43,46,47,48,49,50,51,52,53,54,55,56,57,58,61,62,63,64,65,66,67,68,69,71,72,73,74,75,76,77,80,81,82,83,84,85,86,87,88,89,90,93,96,101,102,103,104,105,106,107,110,111) have mixed types. Specify dtype option on import or set low_memory=False.
  mhc_df = pd.read_csv(mhc_file, header=[0,1], low_memory = True)

,Assay ID - CEDAR IRI,Reference - CEDAR IRI,Reference - Type,Reference - PMID,Reference - Submission ID,Reference - Authors,Reference - Journal,Reference - Date,Reference - Title,Epitope - Epitope IRI,...,Antigen Presenting Cell - Source Tissue,Antigen Presenting Cell - Source Tissue IRI,Antigen Presenting Cell - Name,Antigen Presenting Cell - IRI,Antigen Presenting Cell - Culture Condition,MHC Restriction - Name,MHC Restriction - IRI,MHC Restriction - Evidence Code,MHC Restriction - Evidence IRI,MHC Restriction - Class
0,https://cedar.iedb.org/assay/26,https://cedar.iedb.org/reference/274,Literature,15448372.0,NaN,Yi-Hsiang Huang; Mi-Hua Tao; Cheng-Po Hu; Wan-...,J Gen Virol,2004,Identification of novel HLA-A*0201-restricted ...,https://cedar.iedb.org/epitope/31803,...,NaN,NaN,NaN,NaN,NaN,HLA-A*02:01,http://purl.obolibrary.org/obo/MRO_0001007,NaN,NaN,I
1,https://cedar.iedb.org/assay/534,https://cedar.iedb.org/reference/367,Literature,15368525.0,NaN,P Martin; P Parroche; L Chatel; C Barretto; A ...,J Med Virol,2004,Genetic immunization and comprehensive screeni...,https://cedar.iedb.org/epitope/5033,...,NaN,NaN,NaN,NaN,NaN,HLA-A*02:01,http://purl.obolibrary.org/obo/MRO_0001007,NaN,NaN,I
2,https://cedar.iedb.org/assay/556,https://cedar.iedb.org/reference/375,Literature,15538043.0,NaN,André Jaramillo; Kishore Narayanan; Lacey G Ca...,Breast Cancer Res Treat,2004,Recognition of HLA-A2-restricted mammaglobin-A...,https://cedar.iedb.org/epitope/36773,...,NaN,NaN,NaN,NaN,NaN,HLA-A2,http://purl.obolibrary.org/obo/MRO_0001530,NaN,NaN,I
3,https://cedar.iedb.org/assay/635,https://cedar.iedb.org/reference/386,Literature,15116427.0,NaN,G Kageyama; S Kawano; S Kanagawa; S Kondo; M S...,Rapid Commun Mass Spectrom,2004,Effect of mutated transporters associated with...,https://cedar.iedb.org/epitope/37183,...,lymphoid,http://purl.obolibrary.org/obo/UBERON_0001744,T2 cell (B cell),http://purl.obolibrary.org/obo/CLO_0009242,Cell Line / Clone,HLA-A*02:01,http://purl.obolibrary.org/obo/MRO_0001007,Elution with MHC specific antibody,http://purl.obolibrary.org/obo/ECO_0008039,I
4,https://cedar.iedb.org/assay/638,https://cedar.iedb.org/reference/386,Literature,15116427.0,NaN,G Kageyama; S Kawano; S Kanagawa; S Kondo; M S...,Rapid Commun Mass Spectrom,2004,Effect of mutated transporters associated with...,https://cedar.iedb.org/epitope/37765,...,lymphoid,http://purl.obolibrary.org/obo/UBERON_0001744,T2 cell (B cell),http://purl.obolibrary.org/obo/CLO_0009242,Cell Line / Clone,HLA-A*02:01,http://purl.obolibrary.org/obo/MRO_0001007,Elution with MHC specific antibody,http://purl.obolibrary.org/obo/ECO_0008039,I

In [6]:
mhc_df.columns.tolist()

['Assay ID - CEDAR IRI',
 'Reference - CEDAR IRI',
 'Reference - Type',
 'Reference - PMID',
 'Reference - Submission ID',
 'Reference - Authors',
 'Reference - Journal',
 'Reference - Date',
 'Reference - Title',
 'Epitope - Epitope IRI',
 'Epitope - Object Type',
 'Epitope - Name',
 'Epitope - Reference Name',
 'Epitope - Modified residues',
 'Epitope - Modifications',
 'Epitope - Starting Position',
 'Epitope - Ending Position',
 'Epitope - IRI',
 'Epitope - Synonyms',
 'Epitope - Source Molecule',
 'Epitope - Source Molecule IRI',
 'Epitope - Molecule Parent',
 'Epitope - Molecule Parent IRI',
 'Epitope - Source Organism',
 'Epitope - Source Organism IRI',
 'Epitope - Species',
 'Epitope - Species IRI',
 'Epitope - Mutation',
 'Epitope - Comments',
 'Related Object - Epitope Relation',
 'Related Object - Object Type',
 'Related Object - Name',
 'Related Object - Starting Position',
 'Related Object - Ending Position',
 'Related Object - IRI',
 'Related Object - Synonyms',
 'Related Object - Source Molecule',
 'Related Object - Source Molecule IRI',
 'Related Object - Molecule Parent',
 'Related Object - Molecule Parent IRI',
 'Related Object - Source Organism',
 'Related Object - Source Organism IRI',
 'Related Object - Species',
 'Related Object - Species IRI',
 'Host - Name',
 'Host - IRI',
 'Host - Geolocation',
 'Host - Geolocation IRI',
 'Host - Sex',
 'Host - Age',
 'Host - MHC Types Present',
 'in vivo Process - Process Type',
 'in vivo Process - Disease',
 'in vivo Process - Disease IRI',
 'in vivo Process - Disease Stage',
 'in vivo Antigen - Epitope Relation',
 'in vivo Antigen - Object Type',
 'in vivo Antigen - Name',
 'in vivo Antigen - Reference Name',
 'in vivo Antigen - Starting Position',
 'in vivo Antigen - Ending Position',
 'in vivo Antigen - IRI',
 'in vivo Antigen - Source Molecule',
 'in vivo Antigen - Source Molecule IRI',
 'in vivo Antigen - Molecule Parent',
 'in vivo Antigen - Molecule Parent IRI',
 'in vivo Antigen - Source Organism',
 'in vivo Antigen - Source Organism IRI',
 'in vivo Antigen - Species',
 'in vivo Antigen - Species IRI',
 'in vivo Antigen - Adjuvants',
 'in vivo Antigen - Route',
 'in vivo Antigen - Dose Schedule',
 'In vitro Process - Process Type',
 'In vitro Process - Epitope Relation',
 'In vitro Process - Object Type',
 'In vitro Process - Name',
 'In vitro Process - Reference Name',
 'In vitro Process - Starting Position',
 'In vitro Process - Ending Position',
 'In vitro Process - IRI',
 'In vitro Process - Source Molecule',
 'In vitro Process - Source Molecule IRI',
 'In vitro Process - Molecule Parent',
 'In vitro Process - Molecule Parent IRI',
 'In vitro Process - Source Organism',
 'In vitro Process - Source Organism IRI',
 'In vitro Process - Species',
 'In vitro Process - Species IRI',
 'Antigen Processing - Comments',
 'Assay - Location of Assay Data in Reference',
 'Assay - Method',
 'Assay - Response measured',
 'Assay - Units',
 'Assay - IRI',
 'Assay - Qualitative Measurement',
 'Assay - Measurement Inequality',
 'Assay - Quantitative measurement',
 'Assay - Number of Subjects Tested',
 'Assay - Number of Subjects Responded',
 'Assay - Response Frequency (%)',
 'Assay - PDB ID',
 'Assay - Comments',
 'Antigen Presenting Cell - Source Tissue',
 'Antigen Presenting Cell - Source Tissue IRI',
 'Antigen Presenting Cell - Name',
 'Antigen Presenting Cell - IRI',
 'Antigen Presenting Cell - Culture Condition',
 'MHC Restriction - Name',
 'MHC Restriction - IRI',
 'MHC Restriction - Evidence Code',
 'MHC Restriction - Evidence IRI',
 'MHC Restriction - Class']

In [11]:
#mhc to keep

mhc_keep = [
    #IDENTIFIERS
    "Assay ID - CEDAR IRI", #trace rows
    "Reference - PMID", #reference 

    #EPITOPE INFO
    "Epitope - Epitope IRI", #merge dataset
    "Epitope - Name", #mutant peptide seq
    "Epitope - Mutation", 
    "Epitope - Source Molecule", #source protein
    "Epitope - Starting Position", 
    "Epitope - Ending Position", 

    #related(wt peptide)
    "Related Object - Epitope Relation", #to filter to frame shift
    "Related Object - Name", #wt seq
    "Related Object - Starting Position",
    "Related Object - Ending Position",

    #ASSAY INFO
    "Assay - Method", #different types = different results
    "Assay - Response measured",  
    "Assay - Qualitative Measurement", #positive/neg result
    "Assay - Quantitative measurement", #binding affinity

    #HLA INFO
    "MHC Restriction - Name", #hla allele
    "MHC Restriction - Class", 
    "MHC Restriction - Evidence Code"
    
]

In [12]:
#keep only important columns

mhc_intermediate = mhc_df[mhc_keep].copy()
mhc_intermediate.head()

,Assay ID - CEDAR IRI,Reference - PMID,Epitope - Epitope IRI,Epitope - Name,Epitope - Mutation,Epitope - Source Molecule,Epitope - Starting Position,Epitope - Ending Position,Related Object - Epitope Relation,Related Object - Name,Related Object - Starting Position,Related Object - Ending Position,Assay - Method,Assay - Response measured,Assay - Qualitative Measurement,Assay - Quantitative measurement,MHC Restriction - Name,MHC Restriction - Class,MHC Restriction - Evidence Code
0,https://cedar.iedb.org/assay/26,15448372.0,https://cedar.iedb.org/epitope/31803,KLEDLERDL,NaN,large delta antigen,26.0,34.0,NaN,NaN,NaN,NaN,cellular MHC/direct/fluorescence,qualitative binding,Positive-Low,NaN,HLA-A*02:01,I,NaN
1,https://cedar.iedb.org/assay/534,15368525.0,https://cedar.iedb.org/epitope/5033,ATLGFGAYM,NaN,Genome polyprotein,1260.0,1268.0,NaN,NaN,NaN,NaN,purified MHC/competitive/radioactivity,qualitative binding,Positive,NaN,HLA-A*02:01,I,NaN
2,https://cedar.iedb.org/assay/556,15538043.0,https://cedar.iedb.org/epitope/36773,LIYDSSLCDL,NaN,Mammaglobin-A,83.0,92.0,NaN,NaN,NaN,NaN,cellular MHC/direct/fluorescence,qualitative binding,Positive,NaN,HLA-A2,I,NaN
3,https://cedar.iedb.org/assay/635,15116427.0,https://cedar.iedb.org/epitope/37183,LLDVTAAV,NaN,"interferon, gamma-inducible protein",NaN,NaN,NaN,NaN,NaN,NaN,cellular MHC/mass spectrometry,ligand presentation,Positive,NaN,HLA-A*02:01,I,Elution with MHC specific antibody
4,https://cedar.iedb.org/assay/638,15116427.0,https://cedar.iedb.org/epitope/37765,LLSAEPVPA,NaN,B-cell antigen receptor complex-associated pro...,20.0,28.0,NaN,NaN,NaN,NaN,cellular MHC/mass spectrometry,ligand presentation,Positive,NaN,HLA-A*02:01,I,Elution with MHC specific antibody

In [13]:
#create clean epitope id
mhc_intermediate["epitope_id"] = mhc_intermediate["Epitope - Epitope IRI"].astype(str).str.split("/").str[-1]
mhc_intermediate.head()

,Assay ID - CEDAR IRI,Reference - PMID,Epitope - Epitope IRI,Epitope - Name,Epitope - Mutation,Epitope - Source Molecule,Epitope - Starting Position,Epitope - Ending Position,Related Object - Epitope Relation,Related Object - Name,Related Object - Starting Position,Related Object - Ending Position,Assay - Method,Assay - Response measured,Assay - Qualitative Measurement,Assay - Quantitative measurement,MHC Restriction - Name,MHC Restriction - Class,MHC Restriction - Evidence Code,epitope_id
0,https://cedar.iedb.org/assay/26,15448372.0,https://cedar.iedb.org/epitope/31803,KLEDLERDL,NaN,large delta antigen,26.0,34.0,NaN,NaN,NaN,NaN,cellular MHC/direct/fluorescence,qualitative binding,Positive-Low,NaN,HLA-A*02:01,I,NaN,31803
1,https://cedar.iedb.org/assay/534,15368525.0,https://cedar.iedb.org/epitope/5033,ATLGFGAYM,NaN,Genome polyprotein,1260.0,1268.0,NaN,NaN,NaN,NaN,purified MHC/competitive/radioactivity,qualitative binding,Positive,NaN,HLA-A*02:01,I,NaN,5033
2,https://cedar.iedb.org/assay/556,15538043.0,https://cedar.iedb.org/epitope/36773,LIYDSSLCDL,NaN,Mammaglobin-A,83.0,92.0,NaN,NaN,NaN,NaN,cellular MHC/direct/fluorescence,qualitative binding,Positive,NaN,HLA-A2,I,NaN,36773
3,https://cedar.iedb.org/assay/635,15116427.0,https://cedar.iedb.org/epitope/37183,LLDVTAAV,NaN,"interferon, gamma-inducible protein",NaN,NaN,NaN,NaN,NaN,NaN,cellular MHC/mass spectrometry,ligand presentation,Positive,NaN,HLA-A*02:01,I,Elution with MHC specific antibody,37183
4,https://cedar.iedb.org/assay/638,15116427.0,https://cedar.iedb.org/epitope/37765,LLSAEPVPA,NaN,B-cell antigen receptor complex-associated pro...,20.0,28.0,NaN,NaN,NaN,NaN,cellular MHC/mass spectrometry,ligand presentation,Positive,NaN,HLA-A*02:01,I,Elution with MHC specific antibody,37765

In [14]:
#save intermediate mhc 
mhc_intermediate.to_csv("../../processed/mhc_intermediate.csv", index=False)

In [25]:
#check that rows are unaffected and columns change 

#checking rows and columns
print(len(mhc_df))
print(len(mhc_df.columns))

print(len(mhc_intermediate))
print(len(mhc_intermediate.columns))

4706258
113
4706258
20

In [17]:
#same for tcell dataset

tcell_keep = [
    #IDENTIFIERS
    "Assay ID - CEDAR IRI", #trace rows
    "Reference - PMID", #reference 

    #EPITOPE INFO
    "Epitope - CEDAR IRI", #merge dataset
    "Epitope - Name", #mutant peptide seq
    "Epitope - Mutation", 
    "Epitope - Source Molecule", #source protein

    #related(wt peptide)
    "Related Object - Name", #wt seq
    "Related Object - Epitope Relation", #to filter to frame shift

    #ASSAY INFO
    "Assay - Method", #different types = different results
    "Assay - Response measured",  
    "Assay - Qualitative Measurement", #positive/neg result
    "Assay - Quantitative measurement", #binding affinity

    #HLA INFO
    "MHC Restriction - Name", #hla allele
    "MHC Restriction - Class",

    #effector cell type
    "Effector Cell - Name"
    
]

In [20]:
tcell_intermediate = tcell_df[tcell_keep].copy()
tcell_intermediate.head()

,Assay ID - CEDAR IRI,Reference - PMID,Epitope - CEDAR IRI,Epitope - Name,Epitope - Mutation,Epitope - Source Molecule,Related Object - Name,Related Object - Epitope Relation,Assay - Method,Assay - Response measured,Assay - Qualitative Measurement,Assay - Quantitative measurement,MHC Restriction - Name,MHC Restriction - Class,Effector Cell - Name
0,https://cedar.iedb.org/assay/29,15448372.0,https://cedar.iedb.org/epitope/31803,KLEDLERDL,NaN,large delta antigen,NaN,NaN,multimer/tetramer,qualitative binding,Positive,NaN,HLA-A*02:01,I,splenocyte
1,https://cedar.iedb.org/assay/47,15519708.0,https://cedar.iedb.org/epitope/9203,DLMGYIPLV,NaN,Genome polyprotein,NaN,NaN,51 chromium,cytotoxicity,Positive,NaN,HLA-A*02:01,I,T cell
2,https://cedar.iedb.org/assay/105,15448372.0,https://cedar.iedb.org/epitope/31803,KLEDLERDL,NaN,large delta antigen,NaN,NaN,multimer/tetramer,qualitative binding,Positive,NaN,HLA-A*02:01,I,T cell CD8+
3,https://cedar.iedb.org/assay/107,15448372.0,https://cedar.iedb.org/epitope/31803,KLEDLERDL,NaN,large delta antigen,NaN,NaN,ELISPOT,IFNg release,Positive,NaN,HLA-A*02:01,I,PBMC
4,https://cedar.iedb.org/assay/443,15104676.0,https://cedar.iedb.org/epitope/28958,ITKKVADLVGF,NaN,Melanoma-associated antigen 1,NaN,NaN,51 chromium,cytotoxicity,Positive,NaN,HLA-B*57:02,I,T cell

In [22]:
#also epitope id 

tcell_intermediate["epitope_id"] = tcell_intermediate["Epitope - CEDAR IRI"].astype(str).str.split("/").str[-1]
tcell_intermediate.head()

,Assay ID - CEDAR IRI,Reference - PMID,Epitope - CEDAR IRI,Epitope - Name,Epitope - Mutation,Epitope - Source Molecule,Related Object - Name,Related Object - Epitope Relation,Assay - Method,Assay - Response measured,Assay - Qualitative Measurement,Assay - Quantitative measurement,MHC Restriction - Name,MHC Restriction - Class,Effector Cell - Name,epitope_id
0,https://cedar.iedb.org/assay/29,15448372.0,https://cedar.iedb.org/epitope/31803,KLEDLERDL,NaN,large delta antigen,NaN,NaN,multimer/tetramer,qualitative binding,Positive,NaN,HLA-A*02:01,I,splenocyte,31803
1,https://cedar.iedb.org/assay/47,15519708.0,https://cedar.iedb.org/epitope/9203,DLMGYIPLV,NaN,Genome polyprotein,NaN,NaN,51 chromium,cytotoxicity,Positive,NaN,HLA-A*02:01,I,T cell,9203
2,https://cedar.iedb.org/assay/105,15448372.0,https://cedar.iedb.org/epitope/31803,KLEDLERDL,NaN,large delta antigen,NaN,NaN,multimer/tetramer,qualitative binding,Positive,NaN,HLA-A*02:01,I,T cell CD8+,31803
3,https://cedar.iedb.org/assay/107,15448372.0,https://cedar.iedb.org/epitope/31803,KLEDLERDL,NaN,large delta antigen,NaN,NaN,ELISPOT,IFNg release,Positive,NaN,HLA-A*02:01,I,PBMC,31803
4,https://cedar.iedb.org/assay/443,15104676.0,https://cedar.iedb.org/epitope/28958,ITKKVADLVGF,NaN,Melanoma-associated antigen 1,NaN,NaN,51 chromium,cytotoxicity,Positive,NaN,HLA-B*57:02,I,T cell,28958

In [23]:
#save intermediate tcell 
tcell_intermediate.to_csv("../../processed/tcell_intermediate.csv", index=False)

In [24]:
#checking rows and columns
print(len(tcell_df))
print(len(tcell_df.columns))

print(len(tcell_intermediate))
print(len(tcell_intermediate.columns))

153020
162
153020
16